baseurl = "https://gambler-parks-44416.netlify.com"
title = "Just Docs theme"
languageCode = "en-us"


[params]
    # supported values: "monokai", "github"
    codeTheme = "monokai"

[[menu.main]]
    name = "Docs Home"
    identifier = "docs home"
    pre = "<i class='fa fa-home'></i>"
    url = "/home"
    weight = -220